// LLM tools — the 7 functions the /llm/chat orchestration loop (see
// llmchat.go) can call on the model's behalf, called directly as
// in-process Go functions, not over HTTP: see docs/LLM-INTEGRATION.md
// (once written) / the memory design doc for why this replaced an
// earlier loopback-HTTP-API design (the tool-calling loop turned out not
// to need a separate process boundary at all — llmchat.go runs the whole
// loop inside farsight-server itself).
//
// Every tool call still re-validates tenant scope server-side against
// store, regardless of what device_id/filters an LLM's tool_call
// arguments contain — never trusted alone, an LLM can hallucinate or
// typo a value belonging to another tenant.
package main

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"mime"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"sort"
	"time"

	"github.com/farsight/farsight/internal/influxread"
	"github.com/farsight/farsight/internal/registry"
	"github.com/farsight/farsight/internal/store"
)

const (
	// base64 inflates size ~33%; most vision-capable models cap well
	// below what a bigger source file would need anyway, so this is
	// generous rather than tight.
	maxToolFileBytes = 8 << 20

	defaultSeriesMaxPoints = 200
	hardSeriesMaxPoints    = 1000
	defaultRecordsLimit    = 20
	hardRecordsLimit       = 100

	// Matches the fixed values Telegraf (server-netconfig.sh) and
	// provisionGrafanaOrg's InfluxDB datasource already use — no reason
	// for a fourth place configuring these differently.
	influxBucket = "telemetry"
)

// llmToolsDeps bundles what tool handlers need, passed once rather than
// threading every dependency through every function signature.
type llmToolsDeps struct {
	st         *store.Store
	reg        *registry.Registry
	influx     *influxread.Client
	uploadDir  string
	reportsDir string
	bindIP     string
	httpPort   string
}

type toolFunc func(ctx context.Context, deps llmToolsDeps, tenantID string, args json.RawMessage) (any, error)

var toolDispatch = map[string]toolFunc{
	"list_devices":          toolListDevices,
	"get_device_details":    toolGetDeviceDetails,
	"get_telemetry_summary": toolGetTelemetrySummary,
	"get_telemetry_series":  toolGetTelemetrySeries,
	"search_records":        toolSearchRecords,
	"generate_report":       toolGenerateReport,
	"get_file_content":      toolGetFileContent,
}

// metricInfo is one entry of get_device_details' available_metrics —
// Description is "" when the admin-configured metric descriptions (see
// store.GetMetricDescriptions, editable on /llm-settings) have no entry
// for Name, same device either way, just less guided.
type metricInfo struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
}

// callTool runs toolName in-process (see toolDispatch) and logs it to the
// audit trail — the single entry point llmchat.go's orchestration loop
// uses for every tool_call the model emits. isAdmin/tenant membership is
// checked once per chat turn by the caller (see llmchat.go), not
// per-tool-call here: by the time this runs, "is login allowed to ask
// about tenantID at all" is already established, this only needs to
// answer "does this specific device/record belong to tenantID."
func callTool(ctx context.Context, deps llmToolsDeps, tenantID, login, toolName string, args json.RawMessage) (any, error) {
	fn, ok := toolDispatch[toolName]
	if !ok {
		return nil, fmt.Errorf("unknown tool %q", toolName)
	}
	result, err := fn(ctx, deps, tenantID, args)
	if err != nil {
		return nil, err
	}
	if err := deps.st.LogToolCall(tenantID, login, toolName); err != nil {
		log.Printf("llmtools: audit log failed for %s/%s/%s: %v", tenantID, login, toolName, err)
	}
	return result, nil
}

// llmReportsHandler serves a report generated by the generate_report tool
// — unlike the tools API itself, this runs on the regular Tailscale-facing
// mux (a human needs to download it in a browser), tenant-scoped the same
// way as everything else reachable from there: admins see any report,
// everyone else only their own tenant's.
func llmReportsHandler(st *store.Store, reportsDir string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		tenantID := r.PathValue("tenant")
		filename := path.Base(r.PathValue("filename"))
		if filename == "" || filename == "." || filename == ".." || filename == "/" {
			http.Error(w, "invalid filename", http.StatusBadRequest)
			return
		}

		id := identify(r.Context(), r, st)
		if !id.IsAdmin {
			if _, ok, err := st.RoleForLogin(tenantID, id.Login); err != nil {
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			} else if !ok {
				http.Error(w, "forbidden", http.StatusForbidden)
				return
			}
		}

		w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
		http.ServeFile(w, r, filepath.Join(reportsDir, tenantID, filename))
	}
}

// deviceInTenant loads deviceID's metadata and confirms it belongs to
// tenantID — the one check every device-scoped tool below must pass
// before touching that device's data, regardless of what the LLM asked
// for.
func deviceInTenant(st *store.Store, tenantID, deviceID string) (store.DeviceMeta, error) {
	meta, err := st.GetDevice(deviceID)
	if err != nil {
		return store.DeviceMeta{}, err
	}
	if meta.TenantID != tenantID {
		return store.DeviceMeta{}, fmt.Errorf("device %q is not in tenant %q", deviceID, tenantID)
	}
	return meta, nil
}

// --- 1. list_devices ---

type listDevicesArgs struct {
	OnlineOnly bool `json:"online_only"`
}

type deviceSummary struct {
	DeviceID    string    `json:"device_id"`
	DisplayName string    `json:"display_name"`
	Online      bool      `json:"online"`
	LastSeen    time.Time `json:"last_seen"`
}

func toolListDevices(_ context.Context, deps llmToolsDeps, tenantID string, args json.RawMessage) (any, error) {
	var a listDevicesArgs
	if len(args) > 0 {
		if err := json.Unmarshal(args, &a); err != nil {
			return nil, err
		}
	}

	ids, err := deps.st.DeviceIDsForTenant(tenantID)
	if err != nil {
		return nil, err
	}
	sort.Strings(ids)

	live := map[string]registry.Device{}
	for _, d := range deps.reg.List() {
		live[d.DeviceID] = d
	}

	var out []deviceSummary
	for _, id := range ids {
		meta, err := deps.st.GetDevice(id)
		if err != nil {
			return nil, err
		}
		d := live[id]
		if a.OnlineOnly && !d.Online {
			continue
		}
		out = append(out, deviceSummary{
			DeviceID: id, DisplayName: meta.DisplayName, Online: d.Online, LastSeen: d.LastSeen,
		})
	}
	return map[string]any{"devices": out, "count": len(out)}, nil
}

// --- 2. get_device_details ---

type getDeviceDetailsArgs struct {
	DeviceID string `json:"device_id"`
}

func toolGetDeviceDetails(ctx context.Context, deps llmToolsDeps, tenantID string, args json.RawMessage) (any, error) {
	var a getDeviceDetailsArgs
	if err := json.Unmarshal(args, &a); err != nil {
		return nil, err
	}
	meta, err := deviceInTenant(deps.st, tenantID, a.DeviceID)
	if err != nil {
		return nil, err
	}
	attrs, err := deps.st.GetAttributes(a.DeviceID)
	if err != nil {
		return nil, err
	}

	var online bool
	var lastSeen time.Time
	for _, d := range deps.reg.List() {
		if d.DeviceID == a.DeviceID {
			online, lastSeen = d.Online, d.LastSeen
			break
		}
	}

	// Best-effort: InfluxDB being unreachable shouldn't fail the whole
	// tool call, just leave the discovery fields empty — same spirit as
	// every other external-dependency call in this codebase.
	var metrics []metricInfo
	var recordIDs []string
	if deps.influx != nil {
		if m, err := deps.influx.FieldKeys(ctx, influxBucket, a.DeviceID); err != nil {
			log.Printf("llmtools: field keys failed for %s: %v", a.DeviceID, err)
		} else {
			descriptions, err := deps.st.GetMetricDescriptions()
			if err != nil {
				log.Printf("llmtools: metric descriptions lookup failed: %v", err)
				descriptions = map[string]string{}
			}
			for _, name := range m {
				metrics = append(metrics, metricInfo{Name: name, Description: descriptions[name]})
			}
		}
		if r, err := deps.influx.RecentRecordIDs(ctx, influxBucket, a.DeviceID, 10); err != nil {
			log.Printf("llmtools: recent record ids failed for %s: %v", a.DeviceID, err)
		} else {
			recordIDs = r
		}
	}

	return map[string]any{
		"device_id": a.DeviceID, "display_name": meta.DisplayName, "notes": meta.Notes,
		"online": online, "last_seen": lastSeen,
		"attributes": attrs, "available_metrics": metrics, "recent_record_ids": recordIDs,
	}, nil
}

// --- 3. get_telemetry_summary ---

type telemetryRangeArgs struct {
	DeviceID string `json:"device_id"`
	Metric   string `json:"metric"`
	From     string `json:"from"`
	To       string `json:"to"`
	RecordID string `json:"record_id"`
}

// resolveRange parses From/To (RFC3339), defaulting to the last 24h if
// either is missing/empty — a tool call shouldn't error out just because
// the LLM omitted an optional range.
func resolveRange(from, to string) (time.Time, time.Time, error) {
	now := time.Now().UTC()
	fromT, toT := now.Add(-24*time.Hour), now
	if from != "" {
		t, err := time.Parse(time.RFC3339, from)
		if err != nil {
			return time.Time{}, time.Time{}, fmt.Errorf("invalid from: %w", err)
		}
		fromT = t
	}
	if to != "" {
		t, err := time.Parse(time.RFC3339, to)
		if err != nil {
			return time.Time{}, time.Time{}, fmt.Errorf("invalid to: %w", err)
		}
		toT = t
	}
	return fromT, toT, nil
}

func toolGetTelemetrySummary(ctx context.Context, deps llmToolsDeps, tenantID string, args json.RawMessage) (any, error) {
	var a telemetryRangeArgs
	if err := json.Unmarshal(args, &a); err != nil {
		return nil, err
	}
	if _, err := deviceInTenant(deps.st, tenantID, a.DeviceID); err != nil {
		return nil, err
	}
	if deps.influx == nil {
		return nil, fmt.Errorf("telemetry backend not configured")
	}
	from, to, err := resolveRange(a.From, a.To)
	if err != nil {
		return nil, err
	}

	s, err := deps.influx.Summary(ctx, influxBucket, a.DeviceID, a.Metric, from, to, a.RecordID)
	if err != nil {
		return nil, err
	}
	if s.Count == 0 {
		return map[string]any{
			"count":   0,
			"message": fmt.Sprintf("no telemetry for %q on %q in this range", a.Metric, a.DeviceID),
		}, nil
	}
	return map[string]any{
		"device_id": a.DeviceID, "metric": a.Metric, "from": from, "to": to,
		"count": s.Count, "min": s.Min, "max": s.Max, "avg": s.Avg, "last": s.Last, "last_at": s.LastAt,
	}, nil
}

// --- 4. get_telemetry_series ---

type telemetrySeriesArgs struct {
	telemetryRangeArgs
	MaxPoints int `json:"max_points"`
}

func toolGetTelemetrySeries(ctx context.Context, deps llmToolsDeps, tenantID string, args json.RawMessage) (any, error) {
	var a telemetrySeriesArgs
	if err := json.Unmarshal(args, &a); err != nil {
		return nil, err
	}
	if _, err := deviceInTenant(deps.st, tenantID, a.DeviceID); err != nil {
		return nil, err
	}
	if deps.influx == nil {
		return nil, fmt.Errorf("telemetry backend not configured")
	}
	from, to, err := resolveRange(a.From, a.To)
	if err != nil {
		return nil, err
	}
	maxPoints := a.MaxPoints
	if maxPoints <= 0 {
		maxPoints = defaultSeriesMaxPoints
	}
	if maxPoints > hardSeriesMaxPoints {
		maxPoints = hardSeriesMaxPoints
	}

	points, total, truncated, err := deps.influx.Series(ctx, influxBucket, a.DeviceID, a.Metric, from, to, a.RecordID, maxPoints)
	if err != nil {
		return nil, err
	}
	if total == 0 {
		return map[string]any{
			"count":   0,
			"message": fmt.Sprintf("no telemetry for %q on %q in this range", a.Metric, a.DeviceID),
		}, nil
	}
	return map[string]any{
		"device_id": a.DeviceID, "metric": a.Metric,
		"points": points, "count": len(points), "truncated": truncated, "total_available": total,
	}, nil
}

// --- 5. search_records ---

type searchRecordsArgs struct {
	Filters map[string]string `json:"filters"`
	Limit   int               `json:"limit"`
}

func toolSearchRecords(_ context.Context, deps llmToolsDeps, tenantID string, args json.RawMessage) (any, error) {
	var a searchRecordsArgs
	if err := json.Unmarshal(args, &a); err != nil {
		return nil, err
	}
	if len(a.Filters) == 0 {
		return nil, fmt.Errorf("filters must have at least one field")
	}
	limit := a.Limit
	if limit <= 0 {
		limit = defaultRecordsLimit
	}
	if limit > hardRecordsLimit {
		limit = hardRecordsLimit
	}

	// store.FindRecordsByFilters has no device_id-list scoping of its
	// own (it's a generic any-device filter) — it doesn't paginate
	// either, so every match comes back and tenant scoping + the limit
	// are both applied here, after the fact, never trusting the LLM's
	// filters alone to have stayed within its own tenant.
	allowed, err := deps.st.DeviceIDsForTenant(tenantID)
	if err != nil {
		return nil, err
	}
	allowedSet := map[string]bool{}
	for _, id := range allowed {
		allowedSet[id] = true
	}

	records, err := deps.st.FindRecordsByFilters(a.Filters)
	if err != nil {
		return nil, err
	}

	var scoped []store.RecordMeta
	for _, r := range records {
		if allowedSet[r.DeviceID] {
			scoped = append(scoped, r)
		}
	}

	total := len(scoped)
	truncated := total > limit
	if truncated {
		scoped = scoped[:limit]
	}
	return map[string]any{
		"records": scoped, "count": len(scoped), "truncated": truncated, "total_available": total,
	}, nil
}

// --- 6. generate_report ---

type generateReportArgs struct {
	Title           string `json:"title"`
	ContentMarkdown string `json:"content_markdown"`
}

func toolGenerateReport(_ context.Context, deps llmToolsDeps, tenantID string, args json.RawMessage) (any, error) {
	var a generateReportArgs
	if err := json.Unmarshal(args, &a); err != nil {
		return nil, err
	}
	if a.ContentMarkdown == "" {
		return nil, fmt.Errorf("content_markdown must not be empty")
	}

	dir := filepath.Join(deps.reportsDir, tenantID)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	reportID := fmt.Sprintf("%d", time.Now().UnixNano())
	filename := reportID + ".md"
	if err := os.WriteFile(filepath.Join(dir, filename), []byte(a.ContentMarkdown), 0o644); err != nil {
		return nil, err
	}

	downloadURL := fmt.Sprintf("http://%s:%s/llm/reports/%s/%s", deps.bindIP, deps.httpPort, tenantID, filename)
	return map[string]any{"report_id": reportID, "download_url": downloadURL, "title": a.Title}, nil
}

// --- 7. get_file_content ---

type getFileContentArgs struct {
	DeviceID string `json:"device_id"`
	Filename string `json:"filename"`
}

func toolGetFileContent(_ context.Context, deps llmToolsDeps, tenantID string, args json.RawMessage) (any, error) {
	var a getFileContentArgs
	if err := json.Unmarshal(args, &a); err != nil {
		return nil, err
	}
	if _, err := deviceInTenant(deps.st, tenantID, a.DeviceID); err != nil {
		return nil, err
	}

	// path.Base, same as filesHandler: strips any directory components so
	// a caller-supplied name can't escape the device's own directory.
	filename := path.Base(a.Filename)
	if filename == "" || filename == "." || filename == ".." || filename == "/" {
		return nil, fmt.Errorf("invalid filename")
	}
	filePath := filepath.Join(deps.uploadDir, a.DeviceID, filename)

	info, err := os.Stat(filePath)
	if err != nil {
		return nil, fmt.Errorf("file not found: %w", err)
	}
	if info.Size() > maxToolFileBytes {
		return nil, fmt.Errorf("file too large (%d bytes, max %d) to hand to the model", info.Size(), maxToolFileBytes)
	}

	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, err
	}
	mimeType := mime.TypeByExtension(filepath.Ext(filename))
	if mimeType == "" {
		mimeType = "application/octet-stream"
	}

	return map[string]any{
		"filename": filename, "mime_type": mimeType,
		"data_base64": base64.StdEncoding.EncodeToString(data), "size_bytes": info.Size(),
	}, nil
}
